[project]
name = "weather-dashboard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.1",
    "django-jinja>=2.11.0",
    "requests>=2.32.0",
    "python-dotenv>=1.0.1",
    "djangorestframework>=3.16.1",
    "django-redis>=6.0.0",
]

[dependency-groups]
dev = [
    "black>=26.1.0",
    "isort>=8.0.0",
]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["src"]