# Generated by Django 6.0.1 on 2026-02-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_add_location_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'country')},
        ),
    ]
