# Generated by Django 6.0.1 on 2026-02-21 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_add_unique_city_constraint_to_location_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature_2m", models.FloatField()),
                ("relative_humidity_2m", models.FloatField()),
                ("apparent_temperature", models.FloatField()),
                ("weather_code", models.IntegerField()),
                ("surface_pressure", models.FloatField()),
                ("wind_speed_10m", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_snapshots",
                        to="locations.location",
                    ),
                ),
            ],
        ),
    ]
