# Generated by Django 6.0.1 on 2026-02-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_add_weather_snapshot_model"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="location",
            unique_together={("city", "country"), ("latitude", "longitude")},
        ),
    ]
