# Generated by Django 6.0.1 on 2026-02-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_add_unique_location_constraint_to_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
